# Generated by Django 5.0.14 on 2026-07-05 14:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourism', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('festival', 'Festival'), ('concert', 'Concert'), ('culturel', 'Fête culturelle'), ('sport', 'Sport'), ('foire', 'Foire'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('location_name', models.CharField(blank=True, help_text="Lieu en texte libre si aucun Place n'est associé (ex: 'Palais de la Culture, Abidjan').", max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, help_text='Prix en FCFA. Laisser vide si gratuit.', max_digits=10, null=True)),
                ('booking_url', models.URLField(blank=True, help_text='Lien de réservation/billetterie (optionnel).')),
                ('cover_image_url', models.URLField(blank=True)),
                ('place', models.ForeignKey(blank=True, help_text='Lieu touristique associé (optionnel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tourism.place')),
                ('region', models.ForeignKey(blank=True, help_text="Ville/région de l'événement, utilisée pour le filtre 'autour de lui'.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='tourism.region')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_datetime'], name='events_event_start_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['region'], name='events_event_region_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventparticipation',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_participation_user_event'),
        ),
    ]
